theme: jekyll-theme-time-machine
title: "Workshop on Computational Approaches to Subjectivity, Sentiment & Social Media Analysis"
description: "Subjectivity, Emotion and Sentiment analysis"
show_downloads: false
