theme: jekyll-theme-tactile
title: "Workshop on Computational Approaches to Subjectivity, Sentiment & Social Media Analysis"
description: "Subjectivity, Emotion and Sentiment analysis"
url: https://wassa.github.io/
show_downloads: false
